### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by chisi21** [DerCooleVonDem/BankSystem#1]
ErrorException: "mysqli::__construct(): (HY000/2002): No connection could be made because the target machine actively refused it." (EXCEPTION) in "plugins/BankSystem-main/src/Vazzi/BankSystem/Provider/MySQLProvider" at line 26
Sorry I don't understand the point

**Comment by VazziDE** [comment]
For the Banksystem you need MySQL and you have to edit the login data for it in the config
